### ISSUE TITLE
MAC with disabled DNS can't host locally

### ISSUE THREAD

**Issue by noblewhale** [noblewhale/NobleConnect-public#1]
MAC user specifically disabled DNS services for security, so the call to System.Net.Dns.GetHostEntry(System.Net.Dns.GetHostName()) throws an exception in NobleConnect.Mirror.NobleNetworkManager.OnStartServerLANOnly.  They were trying to run a local server using StartServerLANOnly.

Not sure what to do about that but hopefully something..

**Comment by AnsonKindred** [comment]
Fixed by using network info to find a local address instead of dns. I informed Moon Wizard on discord.
