### ISSUE TITLE
Algenor - Spamming Start/Stop host will quickly use ccu. Clean disconnects not being cleaned up properly?

### ISSUE THREAD

**Issue by noblewhale** [noblewhale/NobleConnect-public#5]
Hi! I'm about to release a game using NobleConnect, but I just noticed something: I had a bug where the client would keep on calling StopHost() and StartHost every couple of seconds. I let it run for about 30 seconds while I was trying to understand the problem, and when I tried to play again I got a "Unhandled error: Forbidden IP" error. I logged in to the dashboard and noticed that it shows my game having 30 connections live, does that mean that any malicious player can just spam requests and make me hit my ccu limit instantly, thus making the game unplayable?

**Comment by AnsonKindred** [comment]
This has been fixed. stop host wasn't getting to send out the revoke allocation message because it was shutting down too fast. I informed Algenor via discord message.
